"""Cria a tabela inicial de dados pluviométricos

Revision ID: e710ee5518ed
Revises: 
Create Date: 2025-10-12 09:57:16.156255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e710ee5518ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pluviometric_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('precipitacao_mm', sa.Float(), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('estacao_codigo', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data', 'estacao_codigo', name='_data_estacao_uc')
    )
    with op.batch_alter_table('pluviometric_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pluviometric_data_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_pluviometric_data_estacao_codigo'), ['estacao_codigo'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pluviometric_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pluviometric_data_estacao_codigo'))
        batch_op.drop_index(batch_op.f('ix_pluviometric_data_data'))

    op.drop_table('pluviometric_data')
    # ### end Alembic commands ###
